/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/blm.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.7, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.textured_1.geometry} material={materials.material0000} />
        <mesh geometry={nodes.textured_2.geometry} material={materials.material0001} />
        <mesh geometry={nodes.textured_3.geometry} material={materials.material0002} />
        <mesh geometry={nodes.textured_4.geometry} material={materials.material0003} />
        <mesh geometry={nodes.textured_5.geometry} material={materials.material0004} />
        <mesh geometry={nodes.textured_6.geometry} material={materials.material0005} />
        <mesh geometry={nodes.textured_7.geometry} material={materials.material0006} />
        <mesh geometry={nodes.textured_8.geometry} material={materials.material0007} />
        <mesh geometry={nodes.textured_9.geometry} material={materials.material0008} />
        <mesh geometry={nodes.textured_10.geometry} material={materials.material0009} />
        <mesh geometry={nodes.textured_11.geometry} material={materials.material0010} />
        <mesh geometry={nodes.textured_12.geometry} material={materials.material0011} />
        <mesh geometry={nodes.textured_13.geometry} material={materials.material0012} />
        <mesh geometry={nodes.textured_14.geometry} material={materials.material0013} />
        <mesh geometry={nodes.textured_15.geometry} material={materials.material0014} />
      </group>
    </group>
  )
}

useGLTF.preload('/blm.glb')
