/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mural7.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh_0.geometry} material={nodes.Mesh_0.material} />
        <mesh geometry={nodes.Mesh_1.geometry} material={nodes.Mesh_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/mural7.glb')
