/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mural8.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.54}>
        <mesh geometry={nodes.Mesh_0001.geometry} material={materials.cropped_textured_mesh_0} />
        <mesh geometry={nodes.Mesh_1001.geometry} material={materials.cropped_textured_mesh_1} />
        <mesh geometry={nodes.Mesh_10.geometry} material={materials.cropped_textured_mesh_6} />
        <mesh geometry={nodes.Mesh_11.geometry} material={materials.cropped_textured_mesh_7} />
        <mesh geometry={nodes.Mesh_12.geometry} material={materials.cropped_textured_mesh_8} />
        <mesh geometry={nodes.Mesh_13.geometry} material={materials.cropped_textured_mesh_9} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.cropped_textured_mesh_10} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.cropped_textured_mesh_11} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.cropped_textured_mesh_12} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials.cropped_textured_mesh_13} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials.cropped_textured_mesh_2} />
        <mesh geometry={nodes.Mesh_7.geometry} material={materials.cropped_textured_mesh_3} />
        <mesh geometry={nodes.Mesh_8.geometry} material={materials.cropped_textured_mesh_4} />
        <mesh geometry={nodes.Mesh_9.geometry} material={materials.cropped_textured_mesh_5} />
      </group>
    </group>
  )
}

useGLTF.preload('/mural8.glb')
