/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mural3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.cropped_textured_mesh_6} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.cropped_textured_mesh_7} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.cropped_textured_mesh_8} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.cropped_textured_mesh_9} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.cropped_textured_mesh_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.cropped_textured_mesh_1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.cropped_textured_mesh_10} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.cropped_textured_mesh_11} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.cropped_textured_mesh_2} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.cropped_textured_mesh_3} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.cropped_textured_mesh_4} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.cropped_textured_mesh_5} />
      </group>
    </group>
  )
}

useGLTF.preload('/mural3.glb')
