/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mural5.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.textured_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.textured_1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.textured_2} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.textured_3} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.textured_4} />
      </group>
    </group>
  )
}

useGLTF.preload('/mural5.glb')
